# Generated by Django 5.1.5 on 2025-01-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_du_temps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miawteachers',
            name='telephone',
            field=models.CharField(max_length=255),
        ),
    ]
