# Generated by Django 5.1.6 on 2025-02-24 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Renseigne un titre', max_length=255)),
                ('content', models.TextField(default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='entre une date de creation')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='entre une date de mise a jour')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='auteur du commentaire', max_length=255)),
                ('content', models.TextField(default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='temps de creation')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.post')),
            ],
        ),
    ]
